# Ruff configuration file
# For more information, see: https://docs.astral.sh/ruff/configuration/

target-version = "py312"

[lint]
select = ["B", "D", "E", "F", "Q", "T"]
ignore = [
    "COM812", # Causes conflicts with formatter
    "D203", # Incompatible formatting
    "D213", # Incompatible formatting
    "T201", # Print needed for CLI
]

[lint.per-file-ignores]
"tests/*" = ["S101"] # Use of assert is standard in tests
